title: Mehdi Karimi
url: https://x86ptr.github.io
baseurl: ""
description: Computer Science and System Security Researcher
  
author:
  name: Mehdi Karimi
  avatar: /assets/images/avatar.jpg
  affiliation: Computer Engineering Student
  university: Payame Noor
  bio: System Security Researcher
  email: x86ptr@gmail.com
  google_scholar: https://scholar.google.com/citations?user=3F-RGisAAAAJ&hl=en
  research_gate: 
  orcid: https://orcid.org/my-orcid?orcid=0009-0003-9811-7177
  github: https://github.com/x86ptr
  linkedin: https://www.linkedin.com/in/x86ptr/
  twitter: https://twitter.com/x86ptr
  about: | 
    I am a third-year computer engineering student at Payame Noor University of Iran. 
    My passion for Cybersecurity has guided my academic objectives and led me to 
    focus on the many areas of software and system security. Throughout my academic journey, 
    I have developed a strong foundation in computer science, 
    with a particular emphasis on the theoretical and practical aspects of software and system security. 
    My research interests lie in the intersection of low-leevl security, where I seek to explore novel 
    approaches to ensuring the integrity and reliability of software systems.

papers:
  - title: A Comprehensive Survey of Code-Reuse Attacks and Exploit Mitigation Mechanisms
    authors: Mehdi Karimi
    publisher: Springer
    journal: Cybersecurity
    publish_date:
    paper_link:
    paper:
    bibtex:
    slide:
    video:
    note: Under Preparation

# talks:
#   - subject:
#     homepage:
#     time:
#     conference:
#     location:
#     slide:
#     video:

# projects:
#   - subject:
#     description:
#     link:
