title: Mehdi Karimi
url: https://x86ptr.github.io
baseurl: ""
description: Computer Science and System Security Researcher
  
author:
  name: Mehdi Karimi
  avatar: /assets/images/avatar.jpg
  affiliation: Computer Engineering Student
  university: Payame Noor
  bio: System Security Researcher
  email: x86ptr@gmail.com
  google_scholar: https://scholar.google.com/citations?user=3F-RGisAAAAJ&hl=en
  research_gate: 
  orcid: https://orcid.org/my-orcid?orcid=0009-0003-9811-7177
  github: https://github.com/x86ptr
  linkedin: https://www.linkedin.com/in/x86ptr/
  twitter: https://twitter.com/x86ptr
  about: | 
    I am a third-year Computer Engineering student at Payame Noor University of Iran, driven by a deep passion for cybersecurity. 
    My academic journey has been shaped by a focus on software and system security, 
    where I have cultivated a strong foundation in both theoretical and practical aspects of computer science. 
    My research interests lie in low-level security, where I aim to explore innovative approaches to ensure the integrity and reliability of software systems.



papers:
  - title: A Comprehensive Survey of Code-Reuse Attacks and Exploit Mitigation Mechanisms
    authors: Mehdi Karimi
    publisher: Springer
    journal: Cybersecurity
    publish_date:
    paper_link:
    paper:
    bibtex:
    slide:
    video:
    note: Under Preparation

# talks:
#   - subject:
#     homepage:
#     time:
#     conference:
#     location:
#     slide:
#     video:

# projects:
#   - subject:
#     description:
#     link:
